### ISSUE TITLE
[Question] package:desktop_multi_window compatibility

### ISSUE THREAD

**Issue by pauli2406** [alexmercerind/media_kit#161]
**Problem:**
Currently, there seems to be an issue when trying to use the Video Player (Video Widget) in combination with multiple windows on macOS. Other platforms I could not verify/test.

When opening a new window and initialising a VideoController, Player and the video Widget the following exception is thrown and a black screen is rendered.

Does this note in the desktop_multi_window library might lead to the issue?

```
The windows run on different flutter engine. So we need use DesktopMultiWindow.invokeMethod and DesktopMultiWindow.invokeMethod to handle method calls between windows.
```

<img width="954" alt="image" src="https://user-images.githubusercontent.com/24795790/234549372-90f18e62-b972-4602-a2c6-45272b5a3838.png">

```bash
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method VideoOutputManager.Create on channel com.alexmercerind/media_kit_video)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      VideoControllerNative.create (package:media_kit_video/src/video_controller_native.dart:81:5)
<asynchronous suspension>
#2      _VideoPlayerState.initState.<anonymous closure> (package:iptv_player/video_player/video_player.dart:38:25)
<asynchronous suspension>
```

if the player.open method is called in the initState nothing happens, except the black screen.
While if added within the build() method it at least plays the sound of the video.

**Expected Behaviour:**

Instead of throwing this exception, the video widget should still render the video and not just play the sound.

**Dependencies:**
```yaml
  desktop_multi_window: ^0.2.0                   # Used for multi window support in Flutter
  media_kit: ^0.0.6                              # Primary package.
  media_kit_video: ^0.0.8                        # For video rendering.
  media_kit_native_event_loop: ^1.0.3            # Support for higher number of concurrent instances & better performance.           # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.4             # macOS package for video native libraries.
```

**Example Code that should help to reproduce:**
<details><summary>Main</summary><p>

```dart

import 'dart:convert';

import 'package:collection/collection.dart';
import 'package:desktop_multi_window/desktop_multi_window.dart';
import 'package:flutter/material.dart';
import 'package:iptv_player/video_player/video_player.dart';
import 'package:media_kit/media_kit.dart';

Future<void> main(List<String> args) async {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  if (args.firstOrNull == 'multi_window') {
    final windowId = int.parse(args[1]);
    final arguments = args[2].isEmpty
        ? const {}
        : jsonDecode(args[2]) as Map<String, dynamic>;
    if (arguments.containsValue('player')) {
      final link = arguments['args1'];
      runApp(
        MaterialApp(
          home: VideoPlayer(
             windowController: WindowController.fromWindowId(windowId),
             videoUrl: link,
             args: {},
            ),
          )
      );
    }
  } else {
    runApp(
      App(),
    );
  }
}


```
</p></details>

<details><summary>Widget to open a new window</summary><p>

```dart

import 'dart:convert';

import 'package:desktop_multi_window/desktop_multi_window.dart';
import 'package:flutter/material.dart';

class OpenNewWindowWidget extends StatelessWidget {
  const OpenNewWindowWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () async {
        final window = await DesktopMultiWindow.createWindow(jsonEncode(
          {
            'args0': 'player',
            'args1': 'https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4',
          },
        ));
        window
          ..setFrame(const Offset(0, 0) & const Size(960, 540))
          ..center()
          ..setTitle("Stream")
          ..show();
      },
      child: Column(children: [
        Expanded(
          child: SizedBox(height:100, width: 100,),
        ),
      ]),
    );
  }
}

```
</p></details>

<details><summary>Video Player Widget that is rendered in the new Window</summary><p>

```dart

import 'package:desktop_multi_window/desktop_multi_window.dart';
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class VideoPlayer extends StatefulWidget {
  const VideoPlayer({
    required this.windowController,
    required this.videoUrl,
    super.key,
  });

  final WindowController windowController;
  final String videoUrl;

  @override
  State<VideoPlayer> createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  final Player player = Player(
    configuration: const PlayerConfiguration(
      logLevel: MPVLogLevel.warn,
    ),
  );

  VideoController? videoController;

  @override
  void initState() {
    super.initState();

    Future.microtask(() async {
      videoController = await VideoController.create(player);
      await player.open(
        Media(widget.videoUrl),
      );
      setState(() {});
    });
  }

  @override
  void dispose() {
    Future.microtask(() async {
      debugPrint('Disposing [Player] and [VideoController]...');
      await player.dispose();
      await videoController?.dispose();
    });
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Video(
        controller: videoController,
      ),
    );
  }
}


```
</p></details>

**Comment by alexmercerind** [comment]
Hi!

First of all, thanks for the descriptive bug report.

I will say this is a bug within desktop_multi_window. Let's forget media_kit for a moment, are you sure that any other native plugins are working inside that newly created window (associated with different engine)?

The log you shared indicates that a connection with native platform implementation could not be established.

The audio playback is working because it does not depend on platform channels. In our architecture, most implementation e.g. most methods, events etc. (including audio) are part of FFI (thus shared across all the platforms). Only video rendering is platform specific & uses platform channels. If platform channel is not working/registered on the new window, I suppose there is very little that can be done by us. The usage of FFI in our project is also a big difference as compared to other plugins. But, video playback & texture registry is something exclusive to platform channels.

**Comment by pauli2406** [comment]
Hi @alexmercerind,

thanks for this fast response!
You might be right, I will check with the authors of that repository if they can share if platform channels would work with multi-window.
Will keep you up to date!

**Comment by pauli2406** [comment]
It is actually possible to use platform channels with the plugin.
https://github.com/MixinNetwork/flutter-plugins/issues/58#issuecomment-1060371162

Adding this into the MainFlutterWindow.swift file now allows me to use the player with video successfully in a new window.

```swift
import desktop_multi_window
import isar_flutter_libs
import macos_ui
import media_kit_libs_macos_video
import media_kit_video
import path_provider_foundation
import screen_retriever
import sqflite
import wakelock_macos
import window_manager

class MainFlutterWindow: NSWindow, NSWindowDelegate {
  override func awakeFromNib() {
    ......
    RegisterGeneratedPlugins(registry: blurryContainerViewController.flutterViewController)

    FlutterMultiWindowPlugin.setOnWindowCreatedCallback { controller in
      FlutterMultiWindowPlugin.register(with: controller.registrar(forPlugin: "FlutterMultiWindowPlugin"))
      IsarFlutterLibsPlugin.register(with: controller.registrar(forPlugin: "IsarFlutterLibsPlugin"))
      MacOSUiPlugin.register(with: controller.registrar(forPlugin: "MacOSUiPlugin"))
      MediaKitLibsMacosVideoPlugin.register(with: controller.registrar(forPlugin: "MediaKitLibsMacosVideoPlugin"))
      MediaKitVideoPlugin.register(with: controller.registrar(forPlugin: "MediaKitVideoPlugin"))
      PathProviderPlugin.register(with: controller.registrar(forPlugin: "PathProviderPlugin"))
      ScreenRetrieverPlugin.register(with: controller.registrar(forPlugin: "ScreenRetrieverPlugin"))
      SqflitePlugin.register(with: controller.registrar(forPlugin: "SqflitePlugin"))
      WakelockMacosPlugin.register(with: controller.registrar(forPlugin: "WakelockMacosPlugin"))
      WindowManagerPlugin.register(with: controller.registrar(forPlugin: "WindowManagerPlugin"))
    }
    ......
  }

```

**Comment by pauli2406** [comment]
Sorry for reopening this one, but after playing around with this combination of packages I found another issue which I think this time applies to this plugin.
If you create multiple new windows, let's say two, next to the main window the plugin runs all of them in a different flutter engine and new runApp() Scope.

Due to this it is required to call ensureInitalized whenever a new window is created that should contain a player. 
```
  MediaKit.ensureInitialized();
```
I realized that opening a new window with a new video player always stopped the playback on the first. The console shows the reason for it. Whenever calling the initalize method again, it seems to clear existing instances.
```cc
media_kit: Destroying 1 [Player] instances...
media_kit: Done.

void MediaKitEventLoopHandler::Initialize() {
  std::lock_guard<std::mutex> l(mutex_);
  if (mutexes_.size() > 0 && promises_.size() > 0) {
    // Destroy already running |mpv_handle|(s).
    std::cout << "media_kit: "
              << "Destroying " << mutexes_.size() << " [Player] instances..."
              << std::endl;
    for (auto& [handle, _] : mutexes_) {
      mpv_command_string(handle, "quit 0");
    }
    std::cout << "media_kit: Done." << std::endl;
    mutexes_.clear();
    promises_.clear();
  }
}
```

Is there another way to allow me to initialise the plugin without stopping existing instances?

**Comment by alexmercerind** [comment]
Hi @pauli2406!

The stopping of existing instances on hot-restart is a "feature" which I implemented in #127. This greatly improves the development experience since that's how hot-restart is meant to work (clearing the existing state & resources).

I don't think I can provide any further support about something which isn't officially supported or endorsed by me i.e. package:desktop_multi_window. However, you can prevent stopping existing instances by commenting following line in your local file:

https://github.com/alexmercerind/media_kit/blob/5e65ba53391ce6921a4d3da26052f9ab32c97933/media_kit/lib/src/libmpv/core/initializer_native_event_loop.dart#L57

Still, you have to keep in mind that it's still not an issue on our end. Our point of focus is video & audio playback, which is infact working in a very stable manner. Multi window support & it's handling is not part of Flutter engine or framework, it's you who is choosing to depend on a third-party package (for which, none of us is liable).

**Comment by Andrekarma** [comment]
Hi @pauli2406 
I am trying to use this library with the "desktop_multi_window" plugin 
I think i am encountiring your same problem. 
Have you found any valid solution?

Commenting the line proposed by @alexmercerind makes the app crash immediatly

**Comment by Andrekarma** [comment]
@alexmercerind do you have any tips or advice on how to solve this? 
If i comment the "_initialize?.call();" the app just crash with no exception thrown

**Comment by Andrekarma** [comment]
@alexmercerind @pauli2406 any help please?

**Comment by pauli2406** [comment]
Hey @Andrekarma 
I decided in the end to not allow more than a second window to be opened.
Whenever I create a new instance I check if their is an existing id already an close that one before:

```dart
try {
                final windowIds = await DesktopMultiWindow.getAllSubWindowIds();
            if (windowIds.isNotEmpty) {
              for (var element in windowIds) {
                await WindowController.fromWindowId(element).close();
              }
            }
            } catch (e) {
              debugPrint(e.toString());
            }
            final window = await DesktopMultiWindow.createWindow(jsonEncode(
              {
                'args0': 'player',
                'link': widget.link,
              },
            ));
            debugPrint('$window');
            window
              ..setFrame(const Offset(0, 0) & const Size(960, 540))
              ..center()
              ..setTitle(widget.title ?? "Stream")
              ..show();
```

To get this running correctly I had to extend my viewer widget with the WindowListener from the window_manager library so that the player is correctly disposed when closing the new window via the close button

```dart
class _VideoPlayerState extends State<VideoPlayer> with WindowListener {
  final Player player = Player(
    configuration: const PlayerConfiguration(
      logLevel: MPVLogLevel.warn,
    ),
  );
  late VideoController videoController;

  @override
  void initState() {
    super.initState();
    windowManager.addListener(this);
    videoController = VideoController(player);
    Future.microtask(() async {
      await player.open(
        Media(widget.videoUrl),
      );
      setState(() {});
    });
  }

  @override
  void dispose() {
    Future.microtask(() async {
      debugPrint('Disposing [Player] and [VideoController]...');
      await player.dispose();
    });
    super.dispose();
  }

  @override
  void onWindowClose() async {
    dispose();
    super.onWindowClose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        if (Navigator.of(context).userGestureInProgress) {
          return false;
        } else {
          return true;
        }
      },
      child: MaterialApp(
        home: Scaffold(
          body: Video(controller: videoController),
        ),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}

```

**Comment by thaidmfinnick** [comment]
Hi @pauli2406, thank you for detail response and support. I follow your instruction and realize that if using `window_manager` with `desktop_multi_window`, closing child window does not free resources as mentioned [in this issue](https://github.com/MixinNetwork/flutter-plugins/issues/293). Have you had experience about this?

Thank you!

**Comment by ZG-123** [comment]
I use the media_kit plugin and desktop_multi_widnow at the same time. When I use the media_kit plugin on a secondary window, the opening and closing of the window will cause the main window to crash. This gives the following error: embedder.cc (2654): 'FlutterEngineMarkExternalTextureFrameAvailable' returned 'kInternalInconsistency'. Could not mark the texture frame as being available.
