### ISSUE TITLE
macOS build fails with - The 'Pods-Runner' target has frameworks with conflicting names

### ISSUE THREAD

**Issue by tomekit** [alexmercerind/media_kit#172]
I am failing to build my Flutter app on macOS (on iOS build works just fine), it fails on pod install:
```
[!] The 'Pods-Runner' target has frameworks with conflicting names: avcodec.xcframework, avfilter.xcframework, avformat.xcframework, avutil.xcframework, crypto.xcframework, mpv.xcframework, ssl.xcframework, swresample.xcframework, swscale.xcframework, and tls.xcframework.
```

Since macOS build fails on installing `window_size` pod (logs below), I've decided to remove it from `pubspec.yaml` temporarily, however it then fails on: `wakelock_macos`.

Any ideas how to resolve this issue?

`window_size` install issue
```
-> Installing window_size (0.0.2)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has frameworks with conflicting names: avcodec.xcframework, avfilter.xcframework, avformat.xcframework, avutil.xcframework, crypto.xcframework, mpv.xcframework, ssl.xcframework, swresample.xcframework, swscale.xcframework, and tls.xcframework.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:67:in `verify_no_duplicate_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:54:in `block (2 levels) in verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:48:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:48:in `block in verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:47:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:47:in `verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:666:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:164:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
         Cloning into '/var/folders/4p/rt_blgvd017_3fp_2h1cb8h40000gn/T/d20230502-76674-56ucx1'...
         Note: switching to '7397e456a68ee344737bf377b1b76ba4fdd7a1fa'.

         You are in 'detached HEAD' state. You can look around, make experimental
         changes and commit them, and you can discard any commits you make in this
         state without impacting any branches by switching back to a branch.

         If you want to create a new branch to retain commits you create, you may
         do so (now or later) by using -c with the switch command. Example:

           git switch -c <new-branch-name>

         Or undo this operation with:

           git switch -

         Turn off this advice by setting config variable advice.detachedHead to false

         Cloning into '/var/folders/4p/rt_blgvd017_3fp_2h1cb8h40000gn/T/d20230502-76674-456wuo'...
         Note: switching to '2479b6f7ff69b66bcdea82184d097667e63828ed'.

         You are in 'detached HEAD' state. You can look around, make experimental
         changes and commit them, and you can discard any commits you make in this
         state without impacting any branches by switching back to a branch.

         If you want to create a new branch to retain commits you create, you may
         do so (now or later) by using -c with the switch command. Example:

           git switch -c <new-branch-name>

         Or undo this operation with:

           git switch -

         Turn off this advice by setting config variable advice.detachedHead to false

         Cloning into '/var/folders/4p/rt_blgvd017_3fp_2h1cb8h40000gn/T/d20230502-76674-1r7ecmd'...
         Note: switching to '2479b6f7ff69b66bcdea82184d097667e63828ed'.

         You are in 'detached HEAD' state. You can look around, make experimental
         changes and commit them, and you can discard any commits you make in this
         state without impacting any branches by switching back to a branch.

         If you want to create a new branch to retain commits you create, you may
         do so (now or later) by using -c with the switch command. Example:

           git switch -c <new-branch-name>

         Or undo this operation with:

           git switch -

         Turn off this advice by setting config variable advice.detachedHead to false

         Cloning into '/var/folders/4p/rt_blgvd017_3fp_2h1cb8h40000gn/T/d20230502-76674-1uw79z1'...
         Note: switching to '4f9164a0a2c9a6a7ff53a2833d54a5c79c957342'.

         You are in 'detached HEAD' state. You can look around, make experimental
         changes and commit them, and you can discard any commits you make in this
         state without impacting any branches by switching back to a branch.

         If you want to create a new branch to retain commits you create, you may
         do so (now or later) by using -c with the switch command. Example:

           git switch -c <new-branch-name>

         Or undo this operation with:

           git switch -

         Turn off this advice by setting config variable advice.detachedHead to false

         % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                        Dload  Upload   Total   Spent    Left  Speed
   100 13.1M  100 13.1M    0     0  3299k      0  0:00:04  0:00:04 --:--:-- 3301k
       configure: WARNING: Can't find Tcl configuration definitions
       configure: WARNING: *** Without Tcl the regression tests cannot be executed ***
       configure: WARNING: *** Consider using --with-tcl=... to define location of Tcl ***

Exception: Error running pod install
```

`wakelock_macos` install issue:
```
-> Installing wakelock_macos (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has frameworks with conflicting names: avcodec.xcframework, avfilter.xcframework, avformat.xcframework, avutil.xcframework, crypto.xcframework, mpv.xcframework, ssl.xcframework, swresample.xcframework, swscale.xcframework, and tls.xcframework.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:67:in `verify_no_duplicate_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:54:in `block (2 levels) in verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:48:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:48:in `block in verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:47:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:47:in `verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:666:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:164:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Exception: Error running pod install
```

Partial `pubspec.yaml`:
```yaml
media_kit: ^0.0.7                              # Primary package.
media_kit_video: ^0.0.9                        # For video rendering.
media_kit_native_event_loop: ^1.0.3            # Support for higher number of concurrent instances & better performance.
media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
media_kit_libs_macos_audio: ^1.0.5             # macOS package for audio native libraries.

window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_sizev
```

flutter --version
```
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (2 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

I am running: `macOS 13.1 M1`

**Comment by birros** [comment]
This is normal, you include `media_kit_libs_macos_video` and `media_kit_libs_macos_audio` in your `pubspec.yaml`, but you can only use one at a time.

If you want video and audio, use `media_kit_libs_macos_video`.
If you only want audio, use `media_kit_libs_macos_audio`.
But not both.

```diff
- media_kit_libs_macos_audio: ^1.0.5
media_kit_libs_macos_video: ^1.0.5
```

**Comment by tomekit** [comment]
Thanks this resolved my issue. I've missed the note about that.
